### PR TITLE
Better code, and add stuff.

### PR DESCRIPTION
**Pull request by Natan515**
I will try to add more stuff and fix stuff and have a better code, my first time.
This first edit is bad ik, its just to start the pull req

### CODE REVIEW

**Comment by 5HT2** [comment]
Strong commits :muscle:

**Comment by Natan515** [comment]
@l1ving STOP BULLYING ME!

**Comment by Natan515** [comment]
Ima remove the .idea at the end dw

**Comment by ghost** [comment]
oh god this commit history. not sure if it's better or worse than the main repo's

**Comment by Natan515** [comment]
No, rn its bad lol, ima fix it

**Comment by Natan515** [comment]
I'm bored and busy so ima close it, i might open it in the future

**Pull request closed without merging**
